services:
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
     - .:/app
     - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: npm run dev